version: '3'

services:
  primary:
    build:
      context: ../
      dockerfile: build/Dockerfile
    ports:
      - "80:8080"
    networks:
      - isolated_network
    environment:
      - APP_MODE=PRIMARY
      - PRIMARY_SERVER_PORT=8080
      - SECONDARY_URLS=http://secondary1:8000,http://secondary2:8000
      - REQUEST_TIMEOUT_MILLISECONDS=100
      - HEALTHCHECK_PERIOD_MILLISECOND=500

  secondary1:
    build:
      context: ../
      dockerfile: build/Dockerfile
    ports:
      - "81:8000"
    networks:
      - isolated_network
    environment:
      - APP_MODE=SECONDARY
      - SECONDARY_SERVER_PORT=8000

  secondary2:
    build:
      context: ../
      dockerfile: build/Dockerfile
    ports:
      - "82:8000"
    networks:
      - isolated_network
    environment:
      - APP_MODE=SECONDARY
      - SECONDARY_SERVER_PORT=8000

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "8051:8080"
    networks:
      - isolated_network
    volumes:
      - ../api:/usr/share/nginx/html/doc
    environment:
      URLS: "[{ url: 'doc/primary.yaml', name: 'Primary'},
             { url: 'doc/secondary.yaml', name: 'Secondary'},
            ]"
      TRY_IT_OUT_ENABLED: "true"

networks:
  isolated_network:
    driver: bridge
