version: '3'

services:
  primary:
    build:
      context: ../
      dockerfile: build/Dockerfile
    networks:
      - isolated_network
    environment:
      - APP_MODE=PRIMARY
      - PRIMARY_SERVER_PORT=8080
      - SECONDARY_URLS=secondary1:8000,secondary2:8000

  secondary1:
    build:
      context: ../
      dockerfile: build/Dockerfile
    networks:
      - isolated_network
    environment:
      - APP_MODE=SECONDARY
      - SECONDARY_SERVER_PORT=8000

  secondary2:
    build:
      context: ../
      dockerfile: build/Dockerfile
    networks:
      - isolated_network
    environment:
      - APP_MODE=SECONDARY
      - SECONDARY_SERVER_PORT=8000

  tester:
    build:
      context: ../
      dockerfile: tests/Dockerfile
    networks:
      - isolated_network
    depends_on:
      - primary
      - secondary1
      - secondary2
    command: pytest .

networks:
  isolated_network:
    driver: bridge