apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nginx-config.yaml
- primary-deployment.yaml
- primary-service.yaml
- secondary-service.yaml
- secondary-statefulset.yaml
- swagger-deployment.yaml
- swagger-service.yaml
namespace: default
images:
- name: replicated-log
  newName: balikfromua/replicated-log
  newTag: 71241bb5b1214df74962994983ec194fe03a2cb3
- name: swagger-ui
  newName: balikfromua/swagger-ui
  newTag: 71241bb5b1214df74962994983ec194fe03a2cb3
