apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx-config.yaml
  - primary-deployment.yaml
  - primary-service.yaml
  - secondary-service.yaml
  - secondary-statefulset.yaml
  - swagger-deployment.yaml
  - swagger-service.yaml
namespace: default
images:
  - name: replicated-log
    newName: balikfromua/replicated-log
    newTag: dev
  - name: swagger-ui
    newName: balikfromua/swagger-ui
    newTag: dev