apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: replicated-log-secondary
spec:
  serviceName: "replicated-log-secondary"
  replicas: 2
  selector:
    matchLabels:
      app: replicated-log
      role: secondary
  template:
    metadata:
      labels:
        app: replicated-log
        role: secondary
    spec:
      containers:
        - name: replicated-log-container
          image: replicated-log
          env:
            - name: APP_MODE
              value: "SECONDARY"
            - name: SECONDARY_SERVER_PORT
              value: "8080"
          ports:
            - containerPort: 8080
