kind: Deployment
apiVersion: apps/v1
metadata:
  name: swagger-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger-docker
          image: swaggerapi/swagger-ui
          env:
            - name: TRY_IT_OUT_ENABLED
              value: "true"
            - name: URLS
              value: "[{ url: 'doc/primary.yaml', name: 'Primary'},
                       { url: 'doc/secondary.yaml', name: 'Secondary'},
                      ]"
          volumeMounts:
            - name: swagger-doc-volume
              mountPath: /usr/share/nginx/html/doc
          ports:
            - containerPort: 80
      volumes:
        - name: swagger-doc-volume
          hostPath:
            path: /home/balik/Desktop/replicated-log/api # todo: make generic
            type: DirectoryOrCreate