apiVersion: v1
kind: Service
metadata:
  name: swagger-service
  labels:
    app: swagger-ui
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31002
  selector:
    app: swagger-ui