openapi: 3.0.3
info:
  title: Secondary
  description: Basic API for secondary servers
  version: 1.0.0
servers:
  - url: /secondary-0
  - url: /secondary-1
components:
  schemas:
    MessageId:
      type: integer
    Message:
      type: object
      nullable: false
      properties:
        order:
          allOf:
            - $ref: '#/components/schemas/MessageId'
            - nullable: false
        message:
          type: string
          nullable: false
paths:
  /api/v1/internal/replicate:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        200:
          description: Replication is successfully done
  /api/v1/messages:
    get:
      responses:
        200:
          description: All messages in order of arrival
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: string
  /api/v1/healthcheck:
    description: "Simple healthcheck mechanism to make retry logic smarter"
    get:
      responses:
        200:
          description: All good!
  /api/test/clean:
    description: "Clean storage. Use only for system testing"
    post:
      responses:
        200:
          description: Success
  /api/test/replication_block:
    description: "Enable or disable the replication on secondary side.
    `enable` set to true blocks all `replicate` requests.
    If `enable` is false then this request will be blocked till all `replicate` requests are unblocked.
    Use only for system testing to emulate delays or failures"
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                enable:
                  type: boolean
      responses:
        200:
          description: Success